# Generated by Django 2.1.7 on 2019-04-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateTimeField(verbose_name='date')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tempapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Credeted_salary', models.IntegerField()),
                ('salary_date', models.DateField()),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tempapp.Hours')),
            ],
        ),
    ]
